# Generated by Django 5.0.6 on 2024-05-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("user",),
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
        migrations.AlterModelTable(
            name="profile",
            table="app_profiles",
        ),
    ]
