# Generated by Django 5.0.6 on 2024-05-14 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                upload_to="image/thumbnails/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "webp", "jpeg", "gif")
                    )
                ],
                verbose_name="Превью поста",
            ),
        ),
    ]
